### ISSUE TITLE
sbi license blurb

### ISSUE THREAD

**Issue by elcorto** [psteinb/c2st#1]
https://github.com/psteinb/c2st/blob/main/c2st/check.py#L1 mentions this code to be part of SBI, is this true?

**Comment by elcorto** [comment]
Also in metrics_test.py .

**Comment by psteinb** [comment]
To be honest, I kept the statement for sake of compatibility mostly. I wouldn't want to exclude the option of `sbi` depending on this package in the future by choosing the wrong license for example. I am happy to remove that statement and replace it with something that gives credit appropriately - while retaining license compatibility.

**Comment by psteinb** [comment]
00dacec
