### ISSUE TITLE
Repeated argument passing

### ISSUE THREAD

**Issue by elcorto** [psteinb/c2st#2]
All args and kwds to `c2st_()` are spelled out and passed to `c2st()`. I suggest using `*args` and `**kwds` plus `functools.wraps` instead. I can send a PR for this.

**Comment by elcorto** [comment]
I think `functools.wraps` copies the whole doc string, so using c2st_'s  in c2st is not correct since they return different things.

Maybe, instead of calling c2st_() in c2st() which does the mean of CV scores, have only one c2st() function and add a `return_scores` keyword such that one returns a tuple `mean(scores), scores` if true or just `mean(scores)` which would be the default.

**Comment by psteinb** [comment]
Making the return value structure depend on a function parameter is not something I would fancy. I makes the API more confusing than necessary from my point of view. In that line of thought `c2st_` versus `c2st` is also not the best API choice in retrospect. I'd have to think about this more.

Maybe something like this could be appropriate:
```
from c2st.check import simple, advanced
#instead of 
from c2st.check import c2st, c2st_
```

**Comment by psteinb** [comment]
Or 
```
from c2st.simple import test_samples
from c2st.advanced import test_samples
```

**Comment by elcorto** [comment]
Having the return signature depend on arguments is frequently done in sklearn and other libs, that's why I thought of that, for instance [`GaussianProcessRegressor.predict`](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#sklearn.gaussian_process.GaussianProcessRegressor.predict) has `return_std` and `return_cov`. Having said that, having two functions to separate functionality is a valid approach, of course.

When going the keyword route outlined above, one could do something like

```py

# default is equal to current API
def c2st(..., return_scores=False):
    ...
    mean_scores = np.atleast_1d(np.mean(scores).astype(np.float32))
    if return_scores:
        return mean_scores, scores
    else:
        return mean_scores

def c2st_(*args, **kwds):
    return c2st(*args, **kwds, return_scores=True)[1]
```

[Here](https://github.com/elcorto/c2st/blob/feature-refactor-api/c2st/check.py#L131) is a prototype of that, along with other things that are outlined in #8.

**Comment by psteinb** [comment]
I think this is resolved since https://github.com/psteinb/c2st/commit/cd0f60ad6a4b39cc2c56f886353aaf194b444bae
Please reopen if needed
