### ISSUE TITLE
Pass classifier and cv splitter instances

### ISSUE THREAD

**Issue by elcorto** [psteinb/c2st#8]
[Here](https://github.com/elcorto/c2st/blob/feature-refactor-api/c2st/check.py) is a prototype which accepts a `clf` class instance, in contrast to `clf_class` and `clf_kwargs`. The same is done for the CV splitter, e.g. `c2st(..., cv=KFold(5))`.

The reasons for that are that (i) at he moment, users have no option to specify another CV splitter and (ii) that the current code passes `random_state` to `clf_class`

```py
clf = clf_class(random_state=seed, **clf_kwargs)
```

which however doesn't work for classifiers that don't have that keyword, such as `KNeighborsClassifier`. Passing class instances  is one way to solve this. Making the code more general that way would also mean to replace `n_folds` and `seed` in something like

```py
c2st(...,
    seed=23,
    n_folds=7,
    clf_class=KNeighborsClassifier, # doesn't work b/c of random_state passed
    clf_kwargs=dict(n_neighbors=8),

    # these don't exist currently
    cv_class=StratifiedKFold,
    cv_kwargs=dict(n_splits=7, shuffle=True)
```

with

```py
c2st(...,
    clf=KNeighborsClassifier(8),
    cv=StratifiedKFold(n_splits=7, shuffle=True, random_state=23)
)
```

Note that in the current prototype, there is some [compatibility code](https://github.com/elcorto/c2st/blob/feature-refactor-api/c2st/check.py#L80) that makes the above along with the current API work such that tests and notebooks run without change for now. Eventually, this has to go of course, which would require to adapt tests and notebooks.

**Comment by psteinb** [comment]
I think this is resolved since https://github.com/psteinb/c2st/commit/cd0f60ad6a4b39cc2c56f886353aaf194b444bae
Please reopen if needed.
